### ISSUE TITLE
"is" does not work properly

### ISSUE THREAD

**Issue by ruv** [Bushmills/yoda#18]
The compilation semantics for `is` are incorrect; they are default at the moment — since this word is defined as an ordinary word:
https://github.com/Bushmills/yoda/blob/d9c3295308c366d2cbca5d9a1dae4cf9f76d9ea2/yoda#L1243-L1252

And it doesn't parse anything in _compilation state_, but [it should](https://forth-standard.org/standard/core/IS). See also the [standard testcase](https://forth-standard.org/standard/testsuite#test:core:IS) for this word.

**Comment by Bushmills** [comment]
Nicely spotted indeed!  
But I'm not going to fix this in this version of `is` because I'm not really happy with this implementation. It's a workaround, mainly meant to be able to revector query and prompt, so I can move the fancier versions of those outside the core source,
But it should be replaced against a less Rube-Goldbergish version sooner or later, which doesn't have the highest priority, because, frankly, I'm not a huge fan of defer, is and related. Therefore I'll leave it unfixed for now and this issue open, so I will remember to check the reimplementation against your observation once it's done.

**Comment by Bushmills** [comment]
new defer/is implementation has hit yoda, which is an improvement over the previous version, IMHO.  At the same time did I make IS compliant with standard, it passes the standard testcase now.
