### ISSUE TITLE
"postpone" does not work properly

### ISSUE THREAD

**Issue by ruv** [Bushmills/yoda#19]
`postpone` should append the compilation semantics of a word, but it appends the execution semantics.
https://github.com/Bushmills/yoda/blob/d9c3295308c366d2cbca5d9a1dae4cf9f76d9ea2/yoda#L1504

Some testing:
```
: foo 123 . ;
: bar postpone foo  ;
see foo
see bar
```

Output:
```
found in forth:
yoda_1413 is a function
yoda_1413 ()
{
    ((s[++sp]=123));
    yoda_1323
}

found in forth:
yoda_1414 is a function
yoda_1414 ()
{
    yoda_1413
}
```

As it shows, `bar` just calls `foo`. But it should compile `foo` (since `foo` is an ordinary word):
```
{
    ((s[++sp]=1413));
    yoda_1342
}
```

See also the [standard testcase](https://forth-standard.org/standard/testsuite#test:core:POSTPONE) for `postpone`.

**Comment by Bushmills** [comment]
That's what I could call a plain blooper, due to me never having really wrapped my head around postpone. I'm a relict from the [compile] and compile time.  
However, this seems like a great opportunity to get the hang of postpone now.  

I've now added "pretend" pseudo code to postpone, which outputs its actions and tells me what result to expect when replacing pseudo against real code. But I'd like to check back with you before I cast it onto code:  

whoami simply helps identifying the words, by showing names and xts.  

foo is the non-immediate word which gets postponed in and by bar.  I reckon the idea of postponing a normal word is to let it compile by an immediate word into a word under construction. Therefore I've made bar immediate.  

According to my newly gained but yet questionable understanding of postpone I expect bar now to compile a call into xyzzy, as the printed "pretend" message indicates.

Here's a screenshot of test code (above the divider line) and the output resulting from running it (below divider). Does that look correct?

![postpone test with pretend output](http://snap.scarydevilmonastery.net/github/1645819158922933898d.png)

**Comment by Bushmills** [comment]
[This release](https://github.com/Bushmills/yoda/commit/69475fdbc53c744e122f7b5492234ddedf6ed677) contains the changes to postpone to let it generate and compile the actual code, rather than just pretending that it does.

**Comment by Bushmills** [comment]
as postpone is passing [this test](https://forth-standard.org/standard/core/POSTPONE) from forth-standard.org, this issue can probably be closed now.  
Note that there's a minor glitch in the test on forth-standard.org:  the first line refers to
a word named GT1 which is just assumed to exist. From context it can be taken that it is presumably meant to be non-immediate `: GT1  123 ;`  
So when trying that test, you need to supply GT1 yourself before compiling further lines from the test.
