### ISSUE TITLE
Division in ANS Forth

### ISSUE THREAD

**Issue by ruv** [Bushmills/yoda#6]
The "Differences" web-page [says at the moment](https://github.com/Bushmills/yoda/wiki/Differences/3e94ce72548e9949346cd08408d055a59b95cdd3
):

> specific words where deviating from ANS

> `/` `mod` `/mod` are truncating, not floored
> I consider changing these to produce floored results

But actually it's **not a deviation** from ANS Forth (Forth-94), and from Forth-2012 too. According to these standards, whether the division is floored or symmetric is [implementation-defined](https://forth-standard.org/standard/doc#subsection.4.1.1) in the mentioned cases.

The only words for which a type of division rounding is specified are [`FM/MOD`](https://forth-standard.org/standard/core/FMDivMOD) and [`SM/REM`](https://forth-standard.org/standard/core/SMDivREM).

**Comment by Bushmills** [comment]
You're right, choice of floored vs symmetric is left to implementor - though I suppose that division should be consistent across all dividing words. This consistency is yoda currently still lacking, given the deviating behaviour of 2/ at this time.  
Maybe I should just change 2/ for now, to achieve consistency, remove this point entirely, and eventually change all to floored (which I do prefer over symmetric). Thank you!

**Comment by ruv** [comment]
Yes, it's very important point that implementation-defined division rounding should be consistent across all corresponding words! Maybe the standard should even require this consistency.

**Comment by Bushmills** [comment]
changed 2/ to yield truncating results in [e39a475](https://github.com/Bushmills/yoda/commit/dbbf0f73a73f7762646ce102deb0276c3a54a685) for now, pending change of all divisions to floored.

**Comment by ruv** [comment]
Concerning the word [`2/`](https://forth-standard.org/standard/core/TwoDiv) — the rounding is not implementation-defined for it.

Actually, the words `2/` and `2*` are specified on a very low level, — they are not division words , but bits shifting words. What they do from division (or multiplication) point of view depends on the [signed number representation](https://forth-standard.org/standard/usage#subsubsection.3.2.1.1) format. And having the [accepted](http://www.forth200x.org/twos-complement.html) two's complement format, `2/` is not equivalent to `2 /` when symmetric rounding is used, since the former produces floored rounding (in contrast, `2*` is equivalent to `2 *` in this case).

Maybe the names `2/` and `2*` are not a good choice, but such is the history.

**Comment by Bushmills** [comment]
right, but there's an additional consideration with this bash implementation:  I don't use the integer bit width as given by the host, bash.  I don't because I'd lose the possibility to distinguish between signed and unsigned numbers, because I'd depend on what bash makes from it - and for bash, all numbers are treated as signed numbers. That's why yoda sets its own integer bit lengths, or rather, the user does, in the configuration. The result is that the most significant bit can be anywhere - and as that bit happens to be used as sign bit, a number which is positive for bash can be negative to yoda.  
That affects of course operations like arithmetic shift right - yoda must take care of the sign bit because bash won't. There simply is no arithmetic right shift operation which I can use as low level operation for right shifting signed numbers. And as I do have to deal with sign myself, I can also see that 2/ is consistent with 2 /, just as bonus without much extra effort.
In case you haven't noticed, there's a "bits" constant in yoda's config, which allows you to set it to anything up to 63 - but also as low as 8, though a system with a signed/unsigned integer range of -128 ... 255 isn't that useful, apart from maybe for testing signed and unsigned operations.  
For `2/` this means currently that I test MSB, and either simply `shift right` (if clear) or  change sign, `and` with maxint, `shift right`, change sign again, and finally `and` with maxuint (if msb is set)
